name: Azure using OIDC

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Login to Azure using OIDC
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secret.AZURE_CLIENT_ID }}
          tenant-id: ${{ secret.AZURE_TENANT_ID }}
          subscription-id: ${{ secret.AZURE_SUBSCRIPTION_ID }}
    - name: Show Azure login info
      run: |
         az account show
         az group list
    - name: Create resource group as a demo
      run: |
         az group create --location uksouth -n MyResourceGroup